"""ArchiveService（04_モジュール設計.md / 要件定義書32, 33節）。

output/{site}/ の内容を ZIP化し、archives/{site}/{site}_YYYYMMDD_HHMMSS.zip
として保存する。archives/ は世代管理専用ディレクトリとし、既存ZIPは
上書きしない（03_ディレクトリ構成.md）。
"""
from __future__ import annotations

import logging
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from src.app.models.site_context_record import SiteContextRecord

logger = logging.getLogger(__name__)


class ArchiveService:
    def archive(self, site_context: SiteContextRecord) -> str:
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        archive_filename = f"{site_context.site_identifier}_{timestamp}.zip"
        archive_path = site_context.archive_dir / archive_filename

        # 生成メタデータの付与（要件定義書34節: Generated by 等）
        source_files = sorted(site_context.output_dir.glob("*"))

        with zipfile.ZipFile(archive_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            for path in source_files:
                if path.is_file():
                    zf.write(path, arcname=path.name)

        logger.info("Archived %s files to %s", len(source_files), archive_path)
        return str(archive_path)
