"""IndexBuilder（要件定義書29節 / 06_処理シーケンス.md SEQ-11）。

Index.md を生成する。titleが欠損している場合はURLで代替表示する。
summaryフィールドは保持しない設計のため、本文先頭から概要を動的に生成する
（05_データ構造設計.md 補足）。
"""
from __future__ import annotations

from typing import Dict, List, Tuple

from src.app.models.page_metadata_record import PageMetadataRecord

SUMMARY_CHAR_LIMIT = 120


class IndexBuilder:
    def build_index(
        self,
        ordered_pages: List[Tuple[str, PageMetadataRecord]],
        page_bodies: Dict[str, str],
        site_identifier: str,
    ) -> str:
        lines = [f"# Index: {site_identifier}", ""]
        lines.append(f"Generated by NotebookLM Document Crawler. {len(ordered_pages)} pages.")
        lines.append("")

        for page_hash, record in ordered_pages:
            display_title = record.title if record.title else record.url  # SEQ-11: URLで代替表示
            body = page_bodies.get(page_hash, "")
            summary = self._build_summary(body)
            lines.append(f"## {display_title}")
            lines.append("")
            lines.append(f"- URL: {record.url}")
            if summary:
                lines.append(f"- Summary: {summary}")
            lines.append("")

        return "\n".join(lines)

    @staticmethod
    def _build_summary(body_markdown: str) -> str:
        text = " ".join(body_markdown.strip().split())
        if len(text) <= SUMMARY_CHAR_LIMIT:
            return text
        return text[:SUMMARY_CHAR_LIMIT].rstrip() + "..."
