name: CI

on:
  push:
    branches: ["*"]
    tags: ["v*.*.*"]
#   pull_request:
#     branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv

      - name: Install Playwright browser
        run: |
          uvx --with-requirements requirements.txt --with-requirements requirements-dev.txt playwright install --with-deps chromium

      - name: Run unit tests with pytest
        run: |
          uvx pytest tests/unit/ -v

      - name: Run integration tests with pytest
        run: |
          uvx pytest tests/integration/docker/ -q

      - name: Run integration tests with e2e
        run: |
          uvx pytest tests/integration/e2e/ -q
